### ISSUE TITLE
Check / Update smart contracts for the security update (8 JUNE TESTNET)

### ISSUE THREAD

**Issue by Luze26** [Metaverse-Football-League/mfl-smart-contracts#38]
https://forum.onflow.org/t/breaking-changes-coming-with-secure-cadence-release/3052

**Comment by ppichier** [comment]
(branch secure-cadence-upgrade)

fix cadence-analyzer tools
check if _libs contracts are the same (contracts + addresses) and update the locally
check all txs and scripts
check dapper whitelisted transactions
